language: csharp
solution: src/IniFileParser.sln

install:
  - ./install.sh
script:
  -  ./build.sh

matrix:
  include:
    - dotnet: 2.1.502
      mono: none
      env: BUILD_TYPE=dotnetcore
    - mono: latest
      dotnet: none
      env: BUILD_TYPE=mono